# Generated by Django 3.0.8 on 2020-07-07 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=128)),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('last_time_updated', models.DateTimeField(auto_now=True)),
                ('expires_in', models.DurationField()),
                ('refresh_token', models.CharField(max_length=128)),
                ('scope', models.CharField(default='identity', max_length=20)),
                ('redirect_uri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('discord_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('avatar', models.CharField(blank=True, max_length=512, null=True)),
                ('token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to='website.DiscordToken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsernameMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.DiscordUser')),
            ],
        ),
    ]
